### ISSUE TITLE
(ERROR) webgl exception

### ISSUE THREAD

**Issue by SwathingSoap** [kiraio-moe/USSR#17] opened 2024-01-15 16:45 UTC
![изображение](https://github.com/kiraio-moe/USSR/assets/51802212/6e68c2d5-27e4-485a-8830-d659d68dac8a)

**Comment by kiraio-moe** [comment] 2024-01-16 00:06
What's your Unity version?

**Comment by SwathingSoap** [comment] 2024-01-16 16:42
Tried on 2023.2.5f and 2021.3.33f same issue

**Comment by kiraio-moe** [comment] 2024-01-23 05:40
> ![изображение](https://private-user-images.githubusercontent.com/51802212/296817082-6e68c2d5-27e4-485a-8830-d659d68dac8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODg2NzYsIm5iZiI6MTcwNTk4ODM3NiwicGF0aCI6Ii81MTgwMjIxMi8yOTY4MTcwODItNmU2OGMyZDUtMjdlNC00ODVhLTg4MzAtZDY1OWQ2OGRhYzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA1MzkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODkyNjg1YTY3ODFhNjdjZDQ5ZDAxMjcyMTVlYmFlNDFhYTY5ZDViOWM5MmIzNjQyNDc4NWZkN2JkZmJhNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qAWgExkqKEhA8RdS0FvLllpmacJMWRbCXIawnJM9vI)

_Duplicate of #6_

**Closed** 2024-01-23 13:48 UTC
